services:
  app:
    build: .
    container_name: mrp_api_server
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/src/app
    environment: # ğŸ‘ˆ ã“ã®3è¡Œã‚’è¿½è¨˜ã—ã¾ã™
      - DATABASE_URL=postgresql://user:password@db:5432/mrp_db
    depends_on: # ğŸ‘ˆ appãŒdbã®å¾Œã«èµ·å‹•ã™ã‚‹ã‚ˆã†ã«è¿½è¨˜ã—ã¾ã™
      - db

  nginx:
    image: nginx:1.25-alpine
    container_name: mrp_web_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: mrp_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mrp_db

volumes:
  postgres_data:
